name: CI
on: [pull_request, push]
jobs:
  mix_test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: "1.10.4"
              otp: "23.x"
          - pair:
              elixir: "1.11.4"
              otp: "23.x"
            lint: lint

    env:
      ELIXIR_ASSERT_TIMEOUT: 350

    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3.0.8
        with:
          path: deps
          key: deps-${{ hashFiles('**/mix.lock') }}
          restore-keys: deps-
      - uses: actions/cache@v3.0.8
        with:
          path: _build
          key: build-${{ runner.os }}-${{ matrix.pair.otp }}-${{ matrix.pair.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: build-${{ runner.os }}-${{ matrix.pair.otp }}-${{ matrix.pair.elixir }}-
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}
      - name: Install Dependencies
        run: mix deps.get
      - name: Check Formatting
        if: ${{ matrix.lint }}
        run: mix format --check-formatted
      - run: mix deps.unlock --check-unused
        if: ${{ matrix.lint }}
      - run: mix deps.compile
      - run: mix compile --warnings-as-errors
        if: ${{ matrix.lint }}
      - name: Run Tests
        run: mix test
